### ISSUE TITLE
Can no longer choose between pairwise and multinomial logistic regression for 3 level outcomes

### ISSUE THREAD

**Issue by ahinton-mmc** [ngreifer/WeightIt#10]
Hi Noah, 

Another potential issue I'm running into today. 

We have a 3 level outcome and I had been able to force weightit to still use a pairwise logistic regression (rather than multinomial logistic regression) by making sure mlogit was not installed, but now I don't seem to have that 'option'. I get an error that stops my code that says "Error in loadNamespace(name) : there is no package called ‘mlogit’".

Trying a reprex again, let's see if I get it right this time.

Is there a way to choose between the two methods?

Thanks! 

``` r

library(tidyverse)
library(WeightIt)
library(Hmisc)
#> Loading required package: lattice
#> Loading required package: survival
#> Loading required package: Formula
#> 
#> Attaching package: 'Hmisc'
#> The following objects are masked from 'package:dplyr':
#> 
#>     src, summarize
#> The following objects are masked from 'package:base':
#> 
#>     format.pval, units
# We do NOT want mlogit installed. Make sure its uninstalled here.
remove.packages("mlogit")  
#> Removing package from '/home/ahinton@mmcf.mehealth.org/R/x86_64-pc-linux-gnu-library/3.5'
#> (as 'lib' is unspecified)
#> Error in find.package(pkgs, lib): there is no package called 'mlogit'

women <- women %>% 
  mutate(height_cat = Hmisc::cut2(height, g=3))

weightit(height ~ weight, data = women, estimand="ATE", method="ps", stabilize=T, include.obj = T)
#> A weightit object
#>  - method: "ps" (propensity score weighting)
#>  - number of obs.: 15
#>  - sampling weights: none
#>  - treatment: continuous
#>  - covariates: weight
weightit(height_cat ~ weight, data = women, estimand="ATE", method="ps", stabilize=T, include.obj = T)
#> Error in loadNamespace(name): there is no package called 'mlogit'
```

<sup>Created on 2020-01-03 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by ngreifer** [comment]
Thank for letting me know about this bug. I'll fix it shortly. You can always request pairwise logistic regressions by setting `use.mlogit = FALSE`, but I agree that there should be a better error message.

**Comment by ahinton-mmc** [comment]
Thank you! I didn’t know about the option. That solves my issue!
