### ISSUE TITLE
Error when using by with super method

### ISSUE THREAD

**Issue by frankpopham** [ngreifer/WeightIt#11]
Hi,

Weightit is great.

 I am finding that I get 
"Error in family$linkfun(mustart) : 
  Argument mu must be a nonempty numeric vector
Error in algorithm SL.glm 
  The Algorithm will be removed from the Super Learner (i.e. given weight 0) 
Error in (function (Y, X, newX = NULL, family = gaussian(), SL.library,  : 
  All algorithms dropped from library".

when using by option for the super method and SL.glm. It runs find without by (i.e. I run on one imputation at a time).

best wishes, Frank

**Comment by ngreifer** [comment]
Thank you so much! If you're using WeightIt with multiple imputation, you should take a look at the MatchThem package, which contains a wrapper for `weightit` for multiply imputed data. I'll take a look at what this bug is about.

**Comment by ngreifer** [comment]
Fixed, thank you!
