### ISSUE TITLE
Is it possible incorporate field PS for CBPS ant GBM?

### ISSUE THREAD

**Issue by Blanch-Font** [ngreifer/WeightIt#2]
The function weightit don't return the propensity score for the CBPS or GBM method. Is it possible to incorporate?

**Comment by ngreifer** [comment]
Fixed! In the version here on github, using `method = "gbm"` or `method = "cbps"` will return propensity scores when the treatment is binary. See the new help files `?method_gbm` and `?method_cbps` for more details. Thank you for the suggestion.
