### ISSUE TITLE
Warning message: deprecated when tidyverse loaded

### ISSUE THREAD

**Issue by hail2thief** [ngreifer/WeightIt#22]
Seems totally minor since output doesn't actually change, but finding that I get a "deprecated" warning when: tidyverse is loaded + using the "cbps" method. PS: thanks for the awesome r package!

    # read libraries
    library(tidyverse)
    library(WeightIt)
    library(cobalt)
    #>  cobalt (Version 4.2.2, Build Date: 2020-06-26 15:50:03 UTC)

    # data
    data("lalonde")

    # example
    out = weightit(treat ~ age + educ + married, data = lalonde, method = "cbps")
    #> Warning: Deprecated
    summary(out)
    #>                  Summary of weights
    #> 
    #> - Weight ranges:
    #> 
    #>            Min                                  Max
    #> treated 2.2741      |----------------------| 6.9730
    #> control 1.1645 |-|                           1.8046
    #> 
    #> - Units with 5 greatest weights by group:
    #>                                            
    #>             182    177    167    124     38
    #>  treated 6.8991 6.9129 6.9267 6.9274  6.973
    #>             604    589    572    541    531
    #>  control 1.7794 1.7807 1.7907 1.7985 1.8046
    #> 
    #> - Weight statistics:
    #> 
    #>         Coef of Var   MAD Entropy # Zeros
    #> treated       0.527 0.411   1.288       0
    #> control       0.185 0.184   0.377       0
    #> overall       0.641 0.384   0.826       0
    #> 
    #> - Effective Sample Sizes:
    #> 
    #>            Control Treated
    #> Unweighted  429.    185.  
    #> Weighted    414.87  144.95

<sup>Created on 2021-03-31 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by ngreifer** [comment]
Figured it out and fixed it. The new version of `WeightIt` is now on CRAN.
