### ISSUE TITLE
Conflict with package logistf

### ISSUE THREAD

**Issue by processna** [ngreifer/WeightIt#25]
I can't figure out why the logistf package conflicts with weightit():

```
install.packages("logistf")
library(logistf)
library(WeightIt)
library(cobalt)
(W1 <- weightit(treat ~ age + educ + married +
                  nodegree + re74, data = lalonde,
                method = "ps", estimand = "ATT"))
```

The error is:
`Error: The treatment and covariates must have the same number of units.`

**Comment by ngreifer** [comment]
Thank you for letting me know about this. A few other users have had the same problem. I'll look into the cause.

**Comment by ngreifer** [comment]
I fixed it. You can install the updated version from GitHub using `devtools::install_github("ngreifer/WeightIt")`.
