### ISSUE TITLE
possible issue 

### ISSUE THREAD

**Issue by chumbleycode** [ngreifer/WeightIt#47]
possible issue - odd error - when calling with estimand ATC 

```
 multiarm <- WeightIt::weightit(X~ Z+ K, 
+                                  data = datall,
+                                  method = "ebal", 
+                                  estimand = "ATC", focal = "4")
```
Error in sweep(covs, 2, targets, check.margin = FALSE) : 
  object 'targets' not found

**Comment by ngreifer** [comment]
Yup, you're right, that's a bug! To fix it, just set `estimand = "ATT"`.

**Comment by chumbleycode** [comment]
Thought so. Just thought I’d let you know anyway, all the best, Justin.
