### ISSUE TITLE
Understanding `get_cont_weights`

### ISSUE THREAD

**Issue by lorenzoFabbri** [ngreifer/WeightIt#49]
This is not an issue/bug. I am just trying to understand how the weights are estimated from the PS, in the case of continuous exposures. In the `get_cont_weights` function ([line 866](https://github.com/ngreifer/WeightIt/blob/8484a507f4e531c8d0610a1e9441cd230a6428be/R/functions_for_processing.R#LL866C1-L866C1)) , the PS is subtracted from the treatment values, and the result is used to the estimate the weights. Why so? I looked into the referenced literature but could not find anything.

**Comment by ngreifer** [comment]
The denominator of the weights is _the conditional density of the treatment given the covariates_ evaluated at the observed values of the treatment. The conditional density of the treatment given the covariates is the density of the errors of the treatment model. The GPS are predicted values from the treatment model, and subtracting them from the treatment gives us the residuals of the treatment model. The distribution of the residuals is an estimate of the distribution of errors, which is equal to the conditional distribution of the treatment given the covariates.

This is described in [Zhu et al. (2015, p4)](https://doi.org/10.1515/jci-2014-0022):

![Screenshot 2023-06-19 at 5 52 41 PM](https://github.com/ngreifer/WeightIt/assets/20465600/6671b589-98a6-4845-979e-6cb03b08481b)

and in [Robins et al. (2000)](https://doi.org/10.1097/00001648-200009000-00011):

![Screenshot 2023-06-19 at 5 58 01 PM](https://github.com/ngreifer/WeightIt/assets/20465600/c15e5380-9d85-4e2f-9378-4594b4c36588)

where $a_{0i}$ is the observed treatment and $\hat\alpha_0 + \hat\alpha_1 l_{0i}$ is the linear predictor in the treatment model with covariate $l_{0}$.
