### ISSUE TITLE
Is this actually G-computation?

### ISSUE THREAD

**Issue by lorenzoFabbri** [ngreifer/WeightIt#50]
With reference to the following [piece of code](https://github.com/ngreifer/WeightIt/blob/8484a507f4e531c8d0610a1e9441cd230a6428be/vignettes/estimating-effects.Rmd#L432), I am wondering whether this is actually G-computation. I thought G-computation would be performed with `marginaleffects::avg_comparisons()`. Aren't those just predicted values of the outcome when the exposure is set to specific values?

**Comment by ngreifer** [comment]
G-computation is a method of estimating a counterfactual mean. It is precisely computing "predicted values of the outcome when the exposure is set to specific values". This is exactly what `avg_predictions()` does. The contrast between two counterfactual means is the treatment effect. `avg_comparisons()` both generates predictions at specific values of the exposure and computes the contrast between the counterfactual means.
