### ISSUE TITLE
Error in `weightit2glm.cont` when providing propensity scores

### ISSUE THREAD

**Issue by taylordunn** [ngreifer/WeightIt#53]
Hello, thanks for the great package. I've run into an error when calculating weights for continuous treatment and provided propensity scores (`ps`)

```
data("lalonde", package = "cobalt")
W.out.c <- WeightIt::weightit(re75 ~ age + educ + race + married +
                                nodegree + re74, 
                              data = lalonde,
                              ps = rep(1, 614),
                              method = "energy")
# Error in weightit2glm.cont(covs = covs, treat = treat, s.weights = s.weights,  : 
#  object 'gp.score' not found
```

Looks like [this code block](https://github.com/ngreifer/WeightIt/blob/master/R/weightit2method.R#L619) needs an `else` statement to set `gp.score <- ps`

**Comment by ngreifer** [comment]
Thanks for the report! This will be fixed in the next version.
