### ISSUE TITLE
`method_user` and the example on the `KBAL`

### ISSUE THREAD

**Issue by BERENZ** [ngreifer/WeightIt#62]
The example for the `KBAL` includes the following lines

```r
    if (is_not_null(focal))
      treat <- as.numeric(treat == focal)
    else
      stop("`estimand` must be \"ATT\" or \"ATC\".", call. = FALSE)
```

This results in an error message, as the 'is_not_null' function is not exported. Changing it to `WeightIt:::is_not_null` solves the problem.

**Comment by ngreifer** [comment]
Thank you so much, I'll make that change in the documentation!

**Comment by BERENZ** [comment]
You may also change `devtools` to `remotes` as it is now suggested way to install packages from GitHub and other repos.
