### ISSUE TITLE
Error when method = "gbm" and stabilize = TRUE

### ISSUE THREAD

**Issue by ulriksartipy** [ngreifer/WeightIt#7]
_From the Examples in the documentation:_ method_gbm {WeightIt}

The following code works as expected
```
(W1 <- weightit(treat ~ age + educ + married +
                  nodegree + re74, data = lalonde,
                method = "gbm", estimand = "ATT",
                stop.method = "es.max"))
```

The addition of the argument "stabilize" produces an error
```
(W1 <- weightit(treat ~ age + educ + married +
                  nodegree + re74, data = lalonde,
                method = "gbm", estimand = "ATT",
                stop.method = "es.max", stabilize = TRUE))
```

Error in tab[t] : invalid subscript type 'closure'

**Comment by ngreifer** [comment]
Thank you! Fixed.

Just so you know, for binary treatments, if you're using weighted regression to estimate treatment effects, it doesn't matter whether you use stabilized weights or not.
